version: "3.3"
services:
  pokemorty:
    container_name: pokemorty
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: yessi
      POSTGRES_PASSWORD: yessi123
      POSTGRES_DB: pokemorty
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - "5434/tcp"
    ports:
      - "5434:5432"